CREATE DATABASE IF NOT EXISTS `db-blog`;
CREATE USER 'user'@'%' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON *.* TO 'user'@'%' WITH GRANT OPTION;
CREATE USER 'user'@'localhost' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON *.* TO 'user'@'localhost' WITH GRANT OPTION;
USE `db-blog`
CREATE TABLE IF NOT EXISTS accounts
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(20),
    psw VARCHAR(20)
);
USE `db-blog`
CREATE TABLE IF NOT EXISTS adds
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    username VARCHAR(20),
	description VARCHAR(20),
	img VARCHAR(20)
);
FLUSH PRIVILEGES;